# Generated by Django 4.2.6 on 2023-11-29 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoría',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=225)),
                ('puntaje', models.FloatField()),
                ('stock', models.IntegerField()),
                ('categoría', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.categoría')),
            ],
        ),
    ]
